### ISSUE TITLE
Wrong Balance

### ISSUE THREAD

**Issue by Jonathan-G555** [hodlwallet/liviano#10]
Sometimes the balance reported by Liviano for the same wallet is different, the next screenshots are from the same wallet in different devices, after wiping out and recovering the wallet the balance changed again, to the same value that were showed by the other device.

**Screenshots**
![image](https://user-images.githubusercontent.com/77517179/151262290-662177c0-a225-4d0e-a839-776c987643f5.png)

![image](https://user-images.githubusercontent.com/77517179/151261147-bfbc6db6-bd20-4930-a968-656f441166d3.png)

![image](https://user-images.githubusercontent.com/77517179/151259087-be2d28ad-39a7-4c0e-859e-723585f44df8.png)

![image](https://user-images.githubusercontent.com/77517179/151259687-a10ab69e-d3a0-4c75-a81d-e9f6bb47544d.png)

**Comment by igorgue** [comment]
I think there's something odd going on here, can you get the `liviano-cli` `--summary` output?
